[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Change this runner as required for your MCU.
runner = "probe-rs run --chip STM32WB55RG"                          # to list chips, run `probe-rs chip list.`
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv7em-none-eabihf"

[env]
# default = "error", other options: trace , debug, warn or off
# to set by module: "warn,{crate}::{mod}=trace"
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "1024"
